// ============================================================
// قائمة العملات (مرتبة أبجديًا حسب الكود)
// ============================================================
export const CURRENCIES = [
    { code: 'AED', name_ar: 'درهم إماراتي', name_en: 'UAE Dirham', symbol_ar: 'د.إ', symbol_en: 'AED' },
    { code: 'AFN', name_ar: 'أفغاني', name_en: 'Afghani', symbol_ar: '؋', symbol_en: 'AFN' },
    { code: 'AZN', name_ar: 'مانات أذربيجاني', name_en: 'Azerbaijani Manat', symbol_ar: '₼', symbol_en: 'AZN' },
    { code: 'BHD', name_ar: 'دينار بحريني', name_en: 'Bahraini Dinar', symbol_ar: 'د.ب', symbol_en: 'BHD' },
    { code: 'BRL', name_ar: 'ريال برازيلي', name_en: 'Brazilian Real', symbol_ar: 'R$', symbol_en: 'BRL' },
    { code: 'CHF', name_ar: 'فرنك سويسري', name_en: 'Swiss Franc', symbol_ar: 'Fr', symbol_en: 'CHF' },
    { code: 'CNY', name_ar: 'يوان صيني', name_en: 'Chinese Yuan', symbol_ar: '¥', symbol_en: 'CNY' },
    { code: 'CZK', name_ar: 'كرونة تشيكية', name_en: 'Czech Koruna', symbol_ar: 'Kč', symbol_en: 'CZK' },
    { code: 'DKK', name_ar: 'كرونة دنماركية', name_en: 'Danish Krone', symbol_ar: 'kr', symbol_en: 'DKK' },
    { code: 'DZD', name_ar: 'دينار جزائري', name_en: 'Algerian Dinar', symbol_ar: 'د.ج', symbol_en: 'DZD' },
    { code: 'EGP', name_ar: 'جنيه مصري', name_en: 'Egyptian Pound', symbol_ar: '£', symbol_en: 'EGP' },
    { code: 'EUR', name_ar: 'يورو', name_en: 'Euro', symbol_ar: '€', symbol_en: 'EUR' },
    { code: 'GBP', name_ar: 'جنيه إسترليني', name_en: 'British Pound', symbol_ar: '£', symbol_en: 'GBP' },
    { code: 'GEL', name_ar: 'لاري جورجي', name_en: 'Georgian Lari', symbol_ar: '₾', symbol_en: 'GEL' },
    { code: 'HUF', name_ar: 'فورنت مجري', name_en: 'Hungarian Forint', symbol_ar: 'Ft', symbol_en: 'HUF' },
    { code: 'IDR', name_ar: 'روبية إندونيسية', name_en: 'Indonesian Rupiah', symbol_ar: 'Rp', symbol_en: 'IDR' },
    { code: 'ILS', name_ar: 'شيكل إسرائيلي', name_en: 'Israeli Shekel', symbol_ar: '₪', symbol_en: 'ILS' },
    { code: 'INR', name_ar: 'روبية هندية', name_en: 'Indian Rupee', symbol_ar: '₹', symbol_en: 'INR' },
    { code: 'IQD', name_ar: 'دينار عراقي', name_en: 'Iraqi Dinar', symbol_ar: 'د.ع', symbol_en: 'IQD' },
    { code: 'IRR', name_ar: 'ريال إيراني', name_en: 'Iranian Rial', symbol_ar: '﷼', symbol_en: 'IRR' },
    { code: 'JOD', name_ar: 'دينار أردني', name_en: 'Jordanian Dinar', symbol_ar: 'د.ا', symbol_en: 'JOD' },
    { code: 'JPY', name_ar: 'ين ياباني', name_en: 'Japanese Yen', symbol_ar: '¥', symbol_en: 'JPY' },
    { code: 'KWD', name_ar: 'دينار كويتي', name_en: 'Kuwaiti Dinar', symbol_ar: 'د.ك', symbol_en: 'KWD' },
    { code: 'KZT', name_ar: 'تينغ كازاخستاني', name_en: 'Kazakhstani Tenge', symbol_ar: '₸', symbol_en: 'KZT' },
    { code: 'LBP', name_ar: 'ليرة لبنانية', name_en: 'Lebanese Pound', symbol_ar: 'ل.ل', symbol_en: 'LBP' },
    { code: 'LYD', name_ar: 'دينار ليبي', name_en: 'Libyan Dinar', symbol_ar: 'ل.د', symbol_en: 'LYD' },
    { code: 'MAD', name_ar: 'درهم مغربي', name_en: 'Moroccan Dirham', symbol_ar: 'د.م.', symbol_en: 'MAD' },
    { code: 'MXN', name_ar: 'بيزو مكسيكي', name_en: 'Mexican Peso', symbol_ar: '$', symbol_en: 'MXN' },
    { code: 'MYR', name_ar: 'رينغيت ماليزي', name_en: 'Malaysian Ringgit', symbol_ar: 'RM', symbol_en: 'MYR' },
    { code: 'NOK', name_ar: 'كرونة نرويجية', name_en: 'Norwegian Krone', symbol_ar: 'kr', symbol_en: 'NOK' },
    { code: 'OMR', name_ar: 'ريال عماني', name_en: 'Omani Rial', symbol_ar: 'ر.ع', symbol_en: 'OMR' },
    { code: 'PHP', name_ar: 'بيزو فلبيني', name_en: 'Philippine Peso', symbol_ar: '₱', symbol_en: 'PHP' },
    { code: 'PKR', name_ar: 'روبية باكستانية', name_en: 'Pakistani Rupee', symbol_ar: '₨', symbol_en: 'PKR' },
    { code: 'PLN', name_ar: 'زلوتي بولندي', name_en: 'Polish Zloty', symbol_ar: 'zł', symbol_en: 'PLN' },
    { code: 'QAR', name_ar: 'ريال قطري', name_en: 'Qatari Riyal', symbol_ar: 'ر.ق', symbol_en: 'QAR' },
    { code: 'RUB', name_ar: 'روبل روسي', name_en: 'Russian Ruble', symbol_ar: '₽', symbol_en: 'RUB' },
    { code: 'SAR', name_ar: 'ريال سعودي', name_en: 'Saudi Riyal', symbol_ar: '﷼', symbol_en: 'SAR' },
    { code: 'SDG', name_ar: 'جنيه سوداني', name_en: 'Sudanese Pound', symbol_ar: 'ج.س', symbol_en: 'SDG' },
    { code: 'SEK', name_ar: 'كرونة سويدية', name_en: 'Swedish Krona', symbol_ar: 'kr', symbol_en: 'SEK' },
    { code: 'SGD', name_ar: 'دولار سنغافوري', name_en: 'Singapore Dollar', symbol_ar: 'S$', symbol_en: 'SGD' },
    { code: 'SYP', name_ar: 'ليرة سورية', name_en: 'Syrian Pound', symbol_ar: 'ل.س', symbol_en: 'SYP' },
    { code: 'THB', name_ar: 'بات تايلاندي', name_en: 'Thai Baht', symbol_ar: '฿', symbol_en: 'THB' },
    { code: 'TND', name_ar: 'دينار تونسي', name_en: 'Tunisian Dinar', symbol_ar: 'د.ت', symbol_en: 'TND' },
    { code: 'TRY', name_ar: 'ليرة تركية', name_en: 'Turkish Lira', symbol_ar: '₺', symbol_en: 'TRY' },
    { code: 'UAH', name_ar: 'هريفنيا أوكرانية', name_en: 'Ukrainian Hryvnia', symbol_ar: '₴', symbol_en: 'UAH' },
    { code: 'USD', name_ar: 'دولار أمريكي', name_en: 'US Dollar', symbol_ar: '$', symbol_en: 'USD' },
    { code: 'VND', name_ar: 'دونغ فيتنامي', name_en: 'Vietnamese Dong', symbol_ar: '₫', symbol_en: 'VND' },
    { code: 'YER', name_ar: 'ريال يمني', name_en: 'Yemeni Rial', symbol_ar: 'ر.ي', symbol_en: 'YER' },
    { code: 'ZAR', name_ar: 'راند جنوب أفريقي', name_en: 'South African Rand', symbol_ar: 'R', symbol_en: 'ZAR' },
];