// ============================================================
// قائمة المناطق الزمنية مع أسماء عربية وإنجليزية
// ============================================================
export const TIMEZONES = [
    { value: 'Africa/Cairo', label_ar: 'القاهرة', label_en: 'Cairo' },
    { value: 'Africa/Casablanca', label_ar: 'الدار البيضاء', label_en: 'Casablanca' },
    { value: 'Africa/Johannesburg', label_ar: 'جوهانسبرغ', label_en: 'Johannesburg' },
    { value: 'Africa/Lagos', label_ar: 'لاغوس', label_en: 'Lagos' },
    { value: 'Africa/Nairobi', label_ar: 'نيروبي', label_en: 'Nairobi' },
    { value: 'America/Anchorage', label_ar: 'أنكوريج', label_en: 'Anchorage' },
    { value: 'America/Argentina/Buenos_Aires', label_ar: 'بوينس آيرس', label_en: 'Buenos Aires' },
    { value: 'America/Bogota', label_ar: 'بوغوتا', label_en: 'Bogota' },
    { value: 'America/Caracas', label_ar: 'كاراكاس', label_en: 'Caracas' },
    { value: 'America/Chicago', label_ar: 'شيكاغو', label_en: 'Chicago' },
    { value: 'America/Denver', label_ar: 'دنفر', label_en: 'Denver' },
    { value: 'America/Los_Angeles', label_ar: 'لوس أنجلوس', label_en: 'Los Angeles' },
    { value: 'America/Mexico_City', label_ar: 'مدينة مكسيكو', label_en: 'Mexico City' },
    { value: 'America/New_York', label_ar: 'نيويورك', label_en: 'New York' },
    { value: 'America/Phoenix', label_ar: 'فينيكس', label_en: 'Phoenix' },
    { value: 'America/Sao_Paulo', label_ar: 'ساو باولو', label_en: 'Sao Paulo' },
    { value: 'America/Toronto', label_ar: 'تورونتو', label_en: 'Toronto' },
    { value: 'Asia/Amman', label_ar: 'عمّان', label_en: 'Amman' },
    { value: 'Asia/Baghdad', label_ar: 'بغداد', label_en: 'Baghdad' },
    { value: 'Asia/Baku', label_ar: 'باكو', label_en: 'Baku' },
    { value: 'Asia/Beirut', label_ar: 'بيروت', label_en: 'Beirut' },
    { value: 'Asia/Damascus', label_ar: 'دمشق', label_en: 'Damascus' },
    { value: 'Asia/Dhaka', label_ar: 'دكا', label_en: 'Dhaka' },
    { value: 'Asia/Dubai', label_ar: 'دبي', label_en: 'Dubai' },
    { value: 'Asia/Hong_Kong', label_ar: 'هونغ كونغ', label_en: 'Hong Kong' },
    { value: 'Asia/Jakarta', label_ar: 'جاكرتا', label_en: 'Jakarta' },
    { value: 'Asia/Karachi', label_ar: 'كراتشي', label_en: 'Karachi' },
    { value: 'Asia/Kathmandu', label_ar: 'كاتماندو', label_en: 'Kathmandu' },
    { value: 'Asia/Kolkata', label_ar: 'كولكاتا', label_en: 'Kolkata' },
    { value: 'Asia/Kuwait', label_ar: 'الكويت', label_en: 'Kuwait' },
    { value: 'Asia/Muscat', label_ar: 'مسقط', label_en: 'Muscat' },
    { value: 'Asia/Riyadh', label_ar: 'الرياض', label_en: 'Riyadh' },
    { value: 'Asia/Seoul', label_ar: 'سيول', label_en: 'Seoul' },
    { value: 'Asia/Shanghai', label_ar: 'شنغهاي', label_en: 'Shanghai' },
    { value: 'Asia/Singapore', label_ar: 'سنغافورة', label_en: 'Singapore' },
    { value: 'Asia/Tehran', label_ar: 'طهران', label_en: 'Tehran' },
    { value: 'Asia/Tokyo', label_ar: 'طوكيو', label_en: 'Tokyo' },
    { value: 'Asia/Yangon', label_ar: 'يانغون', label_en: 'Yangon' },
    { value: 'Atlantic/Reykjavik', label_ar: 'ريكيافيك', label_en: 'Reykjavik' },
    { value: 'Australia/Adelaide', label_ar: 'أديلايد', label_en: 'Adelaide' },
    { value: 'Australia/Brisbane', label_ar: 'بريسبان', label_en: 'Brisbane' },
    { value: 'Australia/Canberra', label_ar: 'كانبرا', label_en: 'Canberra' },
    { value: 'Australia/Perth', label_ar: 'بيرث', label_en: 'Perth' },
    { value: 'Australia/Sydney', label_ar: 'سيدني', label_en: 'Sydney' },
    { value: 'Europe/Amsterdam', label_ar: 'أمستردام', label_en: 'Amsterdam' },
    { value: 'Europe/Athens', label_ar: 'أثينا', label_en: 'Athens' },
    { value: 'Europe/Berlin', label_ar: 'برلين', label_en: 'Berlin' },
    { value: 'Europe/Brussels', label_ar: 'بروكسل', label_en: 'Brussels' },
    { value: 'Europe/Bucharest', label_ar: 'بوخارست', label_en: 'Bucharest' },
    { value: 'Europe/Budapest', label_ar: 'بودابست', label_en: 'Budapest' },
    { value: 'Europe/Copenhagen', label_ar: 'كوبنهاغن', label_en: 'Copenhagen' },
    { value: 'Europe/Dublin', label_ar: 'دبلن', label_en: 'Dublin' },
    { value: 'Europe/Helsinki', label_ar: 'هلسنكي', label_en: 'Helsinki' },
    { value: 'Europe/Istanbul', label_ar: 'إسطنبول', label_en: 'Istanbul' },
    { value: 'Europe/Kiev', label_ar: 'كييف', label_en: 'Kiev' },
    { value: 'Europe/Lisbon', label_ar: 'لشبونة', label_en: 'Lisbon' },
    { value: 'Europe/London', label_ar: 'لندن', label_en: 'London' },
    { value: 'Europe/Madrid', label_ar: 'مدريد', label_en: 'Madrid' },
    { value: 'Europe/Moscow', label_ar: 'موسكو', label_en: 'Moscow' },
    { value: 'Europe/Paris', label_ar: 'باريس', label_en: 'Paris' },
    { value: 'Europe/Prague', label_ar: 'براغ', label_en: 'Prague' },
    { value: 'Europe/Rome', label_ar: 'روما', label_en: 'Rome' },
    { value: 'Europe/Stockholm', label_ar: 'ستوكهولم', label_en: 'Stockholm' },
    { value: 'Europe/Vienna', label_ar: 'فيينا', label_en: 'Vienna' },
    { value: 'Europe/Warsaw', label_ar: 'وارسو', label_en: 'Warsaw' },
    { value: 'Europe/Zurich', label_ar: 'زيورخ', label_en: 'Zurich' },
    { value: 'Pacific/Auckland', label_ar: 'أوكلاند', label_en: 'Auckland' },
    { value: 'Pacific/Guam', label_ar: 'غوام', label_en: 'Guam' },
    { value: 'Pacific/Honolulu', label_ar: 'هونولولو', label_en: 'Honolulu' },
    { value: 'Pacific/Samoa', label_ar: 'ساموا', label_en: 'Samoa' },
    { value: 'UTC', label_ar: 'التوقيت العالمي المنسق', label_en: 'UTC' },
];